name: DevOps CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image (latest)
        run: docker build -t umairas7/my-nginx:latest .

      - name: Build Docker Image (version)
        run: docker build -t umairas7/my-nginx:v1 .

      - name: Push latest
        run: docker push umairas7/my-nginx:latest

      - name: Push version
        run: docker push umairas7/my-nginx:v1

      - name: Done
        run: echo "✅ Image built and pushed automatically 🚀"
